// <auto-generated />
using System;
using ASP.NET_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_API.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240815122844_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_API.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ASP.NET_API.Model.CartItem", b =>
                {
                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShoppingCartID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "ShoppingCartID");

                    b.HasIndex("ShoppingCartID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ASP.NET_API.Model.Order", b =>
                {
                    b.Property<Guid>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderID");

                    b.HasIndex("UserID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ASP.NET_API.Model.OrderItem", b =>
                {
                    b.Property<Guid>("OrderID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ProductID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ASP.NET_API.Model.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("819e0079-69dd-4e5c-9ddf-b23c5badced3"),
                            CategoryID = new Guid("58ea6f54-e71b-48c3-a6f6-82e192018995"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 441, DateTimeKind.Local).AddTicks(8621),
                            Description = "Quia autem aut esse nihil ut optio. Et quo velit sit qui cupiditate. Consequuntur earum sint nobis vel quia.",
                            ImageUrl = "",
                            Price = 54670017,
                            ProductName = "Corporis.",
                            StockQuantity = 3770
                        },
                        new
                        {
                            ProductID = new Guid("7960dc1b-a5e2-497b-9050-80eefff475c8"),
                            CategoryID = new Guid("12e597b6-4a43-4727-b68a-5b0f5338198f"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 441, DateTimeKind.Local).AddTicks(8826),
                            Description = "Natus rerum labore ut ea sed. Dolorem placeat eos assumenda aspernatur quisquam ut tempora. Ab odio exercitationem ex quo. Totam velit nemo et.",
                            ImageUrl = "",
                            Price = 64100814,
                            ProductName = "Enim.",
                            StockQuantity = 2431
                        },
                        new
                        {
                            ProductID = new Guid("bcc176e3-3a9c-4a76-92f6-a46a9c44c47f"),
                            CategoryID = new Guid("b38e6c6d-013b-42ff-a5bc-ffc40f44e331"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 441, DateTimeKind.Local).AddTicks(8899),
                            Description = "Quis temporibus dolores assumenda. Quod voluptas atque pariatur ex nihil voluptatem. Quam sapiente velit eveniet.",
                            ImageUrl = "",
                            Price = 28295692,
                            ProductName = "Dolorum.",
                            StockQuantity = 3513
                        },
                        new
                        {
                            ProductID = new Guid("4658013f-b9c6-4abd-a00a-bc759da19d28"),
                            CategoryID = new Guid("9b103844-3b33-405b-86b1-4f832f7bd370"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 441, DateTimeKind.Local).AddTicks(9100),
                            Description = "Molestiae ipsum eum nam quod eveniet dolore. Magni cum fuga est recusandae fugiat blanditiis. Enim mollitia vel quas atque molestiae quia labore. Expedita incidunt officia ut sint fugiat ipsum in dolor nihil. Minus architecto aspernatur officia id illum in. Unde optio accusantium in dignissimos culpa reprehenderit.",
                            ImageUrl = "",
                            Price = 75184307,
                            ProductName = "Aut.",
                            StockQuantity = 805
                        },
                        new
                        {
                            ProductID = new Guid("e17dd0e4-c2e1-40a6-a74a-11dd61737364"),
                            CategoryID = new Guid("9079d96a-ec4b-4979-b8eb-435d5ef53c60"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 441, DateTimeKind.Local).AddTicks(9194),
                            Description = "Deserunt omnis dicta nam distinctio consectetur non nulla blanditiis voluptas. Magni vero ut ut et tempora ut nam pariatur. Est consectetur et et ratione voluptas non.",
                            ImageUrl = "",
                            Price = 8163043,
                            ProductName = "Consequuntur.",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductID = new Guid("424e008d-d3d4-4414-b2a2-6e30d86de161"),
                            CategoryID = new Guid("9079d96a-ec4b-4979-b8eb-435d5ef53c60"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 441, DateTimeKind.Local).AddTicks(9332),
                            Description = "Eos ullam perferendis et rerum fuga commodi quod. Quis enim ducimus. Laborum sequi aliquam recusandae similique laudantium voluptatem. Ut qui praesentium perferendis excepturi. Nobis voluptas ducimus in impedit nihil.",
                            ImageUrl = "",
                            Price = 22213381,
                            ProductName = "Ab.",
                            StockQuantity = 4140
                        },
                        new
                        {
                            ProductID = new Guid("0965cb87-dbbb-4a9b-bc2c-7c8de9d1e7c4"),
                            CategoryID = new Guid("12e597b6-4a43-4727-b68a-5b0f5338198f"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 441, DateTimeKind.Local).AddTicks(9502),
                            Description = "Eaque corrupti aut animi qui ex quia natus voluptatem quis. Architecto ea qui iste quis labore porro omnis et. Velit soluta reiciendis rerum aut error. Commodi repellendus eius.",
                            ImageUrl = "",
                            Price = 76710518,
                            ProductName = "Corrupti.",
                            StockQuantity = 3134
                        },
                        new
                        {
                            ProductID = new Guid("cfd0e836-9a5d-45a5-b6a1-7c0ede9a4866"),
                            CategoryID = new Guid("ec4a965f-d2b3-4abe-b204-31a1673cfc53"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 441, DateTimeKind.Local).AddTicks(9716),
                            Description = "Corporis voluptas aut consequatur hic ad. Recusandae autem eaque quia accusamus. Officia eius recusandae in cupiditate quo consequatur ut a nulla. Sit adipisci commodi voluptatem veritatis ducimus maxime nesciunt saepe. Recusandae hic ducimus aspernatur deleniti et commodi ipsa ut.",
                            ImageUrl = "",
                            Price = 93376144,
                            ProductName = "Molestiae.",
                            StockQuantity = 2198
                        },
                        new
                        {
                            ProductID = new Guid("32584661-7b84-4612-8041-fed23d5ac475"),
                            CategoryID = new Guid("9079d96a-ec4b-4979-b8eb-435d5ef53c60"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 441, DateTimeKind.Local).AddTicks(9926),
                            Description = "Fugiat tempora dicta officia at error ut sint nemo fuga. Voluptates neque officiis molestiae nostrum sapiente aut aut expedita. Atque ullam quae sint dignissimos.",
                            ImageUrl = "",
                            Price = 85928953,
                            ProductName = "Et.",
                            StockQuantity = 3447
                        },
                        new
                        {
                            ProductID = new Guid("86c852ac-faf1-42bd-83fd-32e0d079298f"),
                            CategoryID = new Guid("ec4a965f-d2b3-4abe-b204-31a1673cfc53"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(12),
                            Description = "Ipsum voluptatem tempora eius distinctio sunt eaque quaerat officia. Qui rem est. Sed ipsum nisi.",
                            ImageUrl = "",
                            Price = 64096448,
                            ProductName = "Ex.",
                            StockQuantity = 2382
                        },
                        new
                        {
                            ProductID = new Guid("7c083059-b390-4ed5-b0a3-e765bccc7296"),
                            CategoryID = new Guid("ec4a965f-d2b3-4abe-b204-31a1673cfc53"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(165),
                            Description = "Aliquid molestiae ipsa libero velit nihil expedita consequatur. Animi doloribus quod aut facilis nihil harum reprehenderit recusandae at. Labore nisi dolorem. Et labore est ut enim. Nulla dignissimos et nihil debitis nostrum et ut fuga iste.",
                            ImageUrl = "",
                            Price = 93285617,
                            ProductName = "Voluptatem.",
                            StockQuantity = 125
                        },
                        new
                        {
                            ProductID = new Guid("1840ebde-fea2-45ed-a719-7120ff26fbaf"),
                            CategoryID = new Guid("ec4a965f-d2b3-4abe-b204-31a1673cfc53"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(273),
                            Description = "Adipisci cupiditate quidem aut dicta. Totam rem corrupti aut. Quisquam voluptas quia. Nemo minus architecto. Perspiciatis aut officia assumenda velit perferendis corrupti nemo exercitationem.",
                            ImageUrl = "",
                            Price = 13344878,
                            ProductName = "Officiis.",
                            StockQuantity = 1072
                        },
                        new
                        {
                            ProductID = new Guid("5329ff04-3f44-47aa-ab42-5c87226b2934"),
                            CategoryID = new Guid("0be413f7-9034-49fc-abe3-d250e88db135"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(404),
                            Description = "Quae dolorem impedit voluptatem autem mollitia reiciendis sequi. Accusamus consectetur eveniet dolores qui ut fuga nostrum aut sed. Nesciunt id facere modi. Mollitia itaque ipsum laboriosam ad at ratione dolores dolores consequuntur. Mollitia rem veniam nesciunt similique a et ut eius.",
                            ImageUrl = "",
                            Price = 11927421,
                            ProductName = "Tenetur.",
                            StockQuantity = 1763
                        },
                        new
                        {
                            ProductID = new Guid("7e63546a-8ac6-403d-8b09-df40fd05fa2b"),
                            CategoryID = new Guid("9079d96a-ec4b-4979-b8eb-435d5ef53c60"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(581),
                            Description = "Quae quo in voluptatum odio velit corrupti enim adipisci distinctio. Illum distinctio perferendis ipsa omnis alias voluptas eligendi accusantium. Dolorem a dolorum sed tenetur at alias officiis dolore. Esse eum aliquid. Enim id distinctio nobis iusto aut velit sunt dolores.",
                            ImageUrl = "",
                            Price = 76092837,
                            ProductName = "Possimus.",
                            StockQuantity = 703
                        },
                        new
                        {
                            ProductID = new Guid("ca580b4f-d42e-4c52-81cb-51160a83086f"),
                            CategoryID = new Guid("5019949c-ca28-49c0-b78f-4edfab60d0db"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(695),
                            Description = "Aliquid non veritatis atque aut. Debitis omnis enim corrupti. Atque qui hic culpa reprehenderit maiores nemo.",
                            ImageUrl = "",
                            Price = 20813613,
                            ProductName = "Rerum.",
                            StockQuantity = 3656
                        },
                        new
                        {
                            ProductID = new Guid("b6ee1cb4-7537-43ae-899e-ce599030adc3"),
                            CategoryID = new Guid("2f9f9268-5c93-49f7-b783-60477a681435"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(802),
                            Description = "Repudiandae dolorum id laudantium vero. Sapiente ut dolorem. Saepe omnis aliquid ut dolore officia iusto. Iure velit aut et aut qui sint quis sequi nobis. Ducimus suscipit aut necessitatibus consequatur sunt atque deleniti.",
                            ImageUrl = "",
                            Price = 41249832,
                            ProductName = "Nisi.",
                            StockQuantity = 4596
                        },
                        new
                        {
                            ProductID = new Guid("1525e829-df3d-4d9d-9561-ba9b419f164c"),
                            CategoryID = new Guid("9079d96a-ec4b-4979-b8eb-435d5ef53c60"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(945),
                            Description = "Aut illo doloremque eaque quidem inventore dolorum exercitationem. Tenetur odio autem. Illum mollitia unde corrupti et. Nostrum vel dolor rerum distinctio. Omnis voluptas aut accusantium eaque dolor cum.",
                            ImageUrl = "",
                            Price = 29236123,
                            ProductName = "Cupiditate.",
                            StockQuantity = 4854
                        },
                        new
                        {
                            ProductID = new Guid("06f29673-ffe4-459d-a93d-a05cdbaa7ecf"),
                            CategoryID = new Guid("ec4a965f-d2b3-4abe-b204-31a1673cfc53"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(1092),
                            Description = "Sint fuga inventore voluptatem enim. Qui iusto veniam. Rerum et molestiae corporis dolore exercitationem minima nihil. Consequatur dolores eos exercitationem. Enim accusantium est voluptas vitae ipsam eveniet. Distinctio nesciunt iure et ut incidunt et.",
                            ImageUrl = "",
                            Price = 83167562,
                            ProductName = "Dicta.",
                            StockQuantity = 1058
                        },
                        new
                        {
                            ProductID = new Guid("0ab9abbe-f0a9-4f26-b3ae-9ab7771ce5b9"),
                            CategoryID = new Guid("9079d96a-ec4b-4979-b8eb-435d5ef53c60"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(1164),
                            Description = "Nesciunt est debitis molestiae. Eligendi eius et occaecati quo expedita sit unde aut dolore. Nobis aliquid ut assumenda vel.",
                            ImageUrl = "",
                            Price = 20683902,
                            ProductName = "Quos.",
                            StockQuantity = 1354
                        },
                        new
                        {
                            ProductID = new Guid("70638512-ca68-468a-871b-072b5c6d57a6"),
                            CategoryID = new Guid("b38e6c6d-013b-42ff-a5bc-ffc40f44e331"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(1221),
                            Description = "Quibusdam suscipit sequi. Quis adipisci quis aut esse saepe. Dicta dolorum cum qui eos.",
                            ImageUrl = "",
                            Price = 32305068,
                            ProductName = "Mollitia.",
                            StockQuantity = 3661
                        },
                        new
                        {
                            ProductID = new Guid("8260105f-f71e-4d41-b227-83cac6674919"),
                            CategoryID = new Guid("12e597b6-4a43-4727-b68a-5b0f5338198f"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(1353),
                            Description = "Unde cupiditate possimus occaecati sit nulla hic laboriosam. Eum recusandae facilis nihil qui consequatur ducimus quis eos voluptatem. Eum iure aliquid ut ut sunt autem quasi hic. Minima autem cumque dolores.",
                            ImageUrl = "",
                            Price = 78511471,
                            ProductName = "Nobis.",
                            StockQuantity = 3151
                        },
                        new
                        {
                            ProductID = new Guid("54bb077f-a0a8-4a35-9d24-a889d3d7a895"),
                            CategoryID = new Guid("0be413f7-9034-49fc-abe3-d250e88db135"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(1506),
                            Description = "Nesciunt beatae non quas voluptatem reiciendis. Alias assumenda officiis ducimus sit. Culpa fugiat neque quia corrupti quia. Illo aut reprehenderit dolor. Iste rerum nostrum et id qui iusto. Qui est facere blanditiis nulla.",
                            ImageUrl = "",
                            Price = 11616105,
                            ProductName = "Pariatur.",
                            StockQuantity = 1855
                        },
                        new
                        {
                            ProductID = new Guid("89263a97-8cee-4f9a-b050-e325aeb789eb"),
                            CategoryID = new Guid("12e597b6-4a43-4727-b68a-5b0f5338198f"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(1574),
                            Description = "Id explicabo tenetur. Corporis dolorum blanditiis. Tempore fuga iure minima. Voluptatem tenetur deserunt doloremque delectus velit aperiam illo.",
                            ImageUrl = "",
                            Price = 915736,
                            ProductName = "Autem.",
                            StockQuantity = 4531
                        },
                        new
                        {
                            ProductID = new Guid("3ddab5c4-b3b1-4521-9069-cb054b099c61"),
                            CategoryID = new Guid("5019949c-ca28-49c0-b78f-4edfab60d0db"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(1682),
                            Description = "Sit quis aut in quaerat qui ipsam quae. Id dolorem maiores dolor minima soluta. Et et sit et nemo saepe cupiditate laboriosam officiis.",
                            ImageUrl = "",
                            Price = 59237929,
                            ProductName = "Ut.",
                            StockQuantity = 1318
                        },
                        new
                        {
                            ProductID = new Guid("94add515-3e71-4da8-8d0d-50d78fca5f63"),
                            CategoryID = new Guid("12e597b6-4a43-4727-b68a-5b0f5338198f"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(1769),
                            Description = "Voluptatem modi repudiandae consequuntur voluptas. Modi consequuntur eligendi quis aut dolores doloribus quia reiciendis. Facere quis dolore.",
                            ImageUrl = "",
                            Price = 25513313,
                            ProductName = "Est.",
                            StockQuantity = 868
                        },
                        new
                        {
                            ProductID = new Guid("679afb9d-19e8-4c68-81a0-251da50541bb"),
                            CategoryID = new Guid("9079d96a-ec4b-4979-b8eb-435d5ef53c60"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(1957),
                            Description = "Pariatur laudantium non libero voluptatem exercitationem. Ut aliquam cum voluptas ut. Repudiandae saepe molestiae corporis. Optio sed in provident magni saepe sunt molestias.",
                            ImageUrl = "",
                            Price = 64925573,
                            ProductName = "Aut.",
                            StockQuantity = 2402
                        },
                        new
                        {
                            ProductID = new Guid("0cc28e4f-10ad-46a4-8a77-867b56615927"),
                            CategoryID = new Guid("12e597b6-4a43-4727-b68a-5b0f5338198f"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(2148),
                            Description = "Molestias est sint voluptate. Praesentium autem architecto repellendus tempora minus provident numquam. Animi praesentium ex eum officiis consequatur ipsam sed eaque. Sit harum explicabo consequatur facilis. Suscipit beatae dolorem omnis omnis laudantium repellat atque minus.",
                            ImageUrl = "",
                            Price = 84182394,
                            ProductName = "Quia.",
                            StockQuantity = 1305
                        },
                        new
                        {
                            ProductID = new Guid("089657ad-aca2-4063-bb61-55567ce9b8ef"),
                            CategoryID = new Guid("58ea6f54-e71b-48c3-a6f6-82e192018995"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(2280),
                            Description = "Animi soluta qui voluptates consectetur consequuntur odit corporis et. Nemo et animi architecto veritatis commodi error molestiae earum saepe. Commodi distinctio asperiores dolores praesentium accusamus aspernatur doloremque.",
                            ImageUrl = "",
                            Price = 74524844,
                            ProductName = "Quam.",
                            StockQuantity = 3461
                        },
                        new
                        {
                            ProductID = new Guid("b9b94eaf-0bb0-4a9a-8b37-1e189f148575"),
                            CategoryID = new Guid("12e597b6-4a43-4727-b68a-5b0f5338198f"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(2444),
                            Description = "Tenetur ad ut blanditiis quo tempora omnis libero. Qui vel in velit libero voluptatum optio consectetur. Minima ratione labore sit eum est. Quaerat aut ad possimus quia cupiditate dolor vitae. Aut sunt distinctio aut incidunt.",
                            ImageUrl = "",
                            Price = 66516074,
                            ProductName = "Accusamus.",
                            StockQuantity = 4381
                        },
                        new
                        {
                            ProductID = new Guid("e662cfa0-7936-4b8c-bb79-bd3bf125084b"),
                            CategoryID = new Guid("58ea6f54-e71b-48c3-a6f6-82e192018995"),
                            CreatedDate = new DateTime(2024, 8, 15, 19, 28, 43, 442, DateTimeKind.Local).AddTicks(2553),
                            Description = "Veritatis praesentium molestiae omnis quae. Nemo officia consequatur quos recusandae ducimus. Est blanditiis eius quas. Qui non doloremque ipsam et iste iure eaque eius et. Enim perspiciatis perferendis quis qui libero et.",
                            ImageUrl = "",
                            Price = 58001584,
                            ProductName = "Consequatur.",
                            StockQuantity = 3606
                        });
                });

            modelBuilder.Entity("ASP.NET_API.Model.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCategoryID");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            ProductCategoryID = new Guid("5019949c-ca28-49c0-b78f-4edfab60d0db"),
                            CategoryName = "Rerum.",
                            CategoryShortDescription = "Ipsa est quasi. Sit temporibus perferendis ut molestiae tenetur adipisci aliquid. Quas quidem ab possimus eveniet fugit et repellat."
                        },
                        new
                        {
                            ProductCategoryID = new Guid("ec4a965f-d2b3-4abe-b204-31a1673cfc53"),
                            CategoryName = "Distinctio.",
                            CategoryShortDescription = "Necessitatibus blanditiis eligendi ea asperiores deleniti sed. Iure odio voluptatem corrupti aperiam eos. Et et totam officiis et aperiam."
                        },
                        new
                        {
                            ProductCategoryID = new Guid("2f9f9268-5c93-49f7-b783-60477a681435"),
                            CategoryName = "Omnis.",
                            CategoryShortDescription = "Ea ipsa quasi at est esse aperiam vel mollitia. Id officiis explicabo est voluptates hic. Est sapiente corporis atque ratione sit eveniet laudantium ab. Provident temporibus aut iste magni. Non repellat tenetur velit ut est ut ea facilis saepe."
                        },
                        new
                        {
                            ProductCategoryID = new Guid("b38e6c6d-013b-42ff-a5bc-ffc40f44e331"),
                            CategoryName = "Omnis.",
                            CategoryShortDescription = "Aut quidem iste molestiae incidunt quaerat quibusdam. Minima quaerat accusantium ipsum. Est quae et officia atque molestiae."
                        },
                        new
                        {
                            ProductCategoryID = new Guid("9b103844-3b33-405b-86b1-4f832f7bd370"),
                            CategoryName = "Est.",
                            CategoryShortDescription = "Est tenetur sed similique. Doloribus ut quo aliquam. Omnis ut architecto id aut et. Exercitationem sit minus est quod non labore debitis molestiae molestiae. Illo voluptate fuga excepturi et vel accusantium id iure distinctio. Aut enim dignissimos alias."
                        },
                        new
                        {
                            ProductCategoryID = new Guid("b91e8ba3-a5b4-4278-b055-b6e1c8ef4b87"),
                            CategoryName = "Iste.",
                            CategoryShortDescription = "Est nemo non est animi et. Velit excepturi et voluptatem ullam. Velit et repellat repellendus nulla voluptas voluptatem ad. Impedit quis deleniti eius neque."
                        },
                        new
                        {
                            ProductCategoryID = new Guid("12e597b6-4a43-4727-b68a-5b0f5338198f"),
                            CategoryName = "Non.",
                            CategoryShortDescription = "Id quis nulla reprehenderit. Et autem sit consequatur asperiores. Molestiae ullam neque culpa. Delectus recusandae id."
                        },
                        new
                        {
                            ProductCategoryID = new Guid("58ea6f54-e71b-48c3-a6f6-82e192018995"),
                            CategoryName = "Ipsam.",
                            CategoryShortDescription = "Quo magni non iure. Sequi et vel totam placeat dolor corporis. Et qui corporis et. Dolorum qui eaque nulla doloremque nulla. Unde temporibus reprehenderit aliquam tempora temporibus odit omnis culpa expedita."
                        },
                        new
                        {
                            ProductCategoryID = new Guid("0be413f7-9034-49fc-abe3-d250e88db135"),
                            CategoryName = "Quo.",
                            CategoryShortDescription = "Sit modi dicta molestiae non atque est repellat aperiam non. Nam perferendis quis optio quia sed et aut. Molestiae illo consequatur at consequuntur."
                        },
                        new
                        {
                            ProductCategoryID = new Guid("9079d96a-ec4b-4979-b8eb-435d5ef53c60"),
                            CategoryName = "Labore.",
                            CategoryShortDescription = "Facere unde asperiores quod consequuntur aperiam et in. Laborum voluptatem perspiciatis velit sapiente. Eos possimus deserunt numquam et velit nisi. Temporibus laborum illum praesentium sapiente vero. Ullam quis occaecati aut. Corrupti itaque saepe ut."
                        });
                });

            modelBuilder.Entity("ASP.NET_API.Model.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiriedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("ASP.NET_API.Model.ShoppingCart", b =>
                {
                    b.Property<Guid>("ShoppingCartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ShoppingCartID");

                    b.HasIndex("UserID");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("ASP.NET_API.Model.WishList", b =>
                {
                    b.Property<Guid>("WishListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WishListID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("WishList");
                });

            modelBuilder.Entity("ASP.NET_API.Model.WishListItem", b =>
                {
                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WishListID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductID", "WishListID");

                    b.HasIndex("WishListID");

                    b.ToTable("WishListItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "73de7301-0fdd-4b00-9501-6cf6a1f0b7d9",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "be5dd9f3-a8b6-4dc0-a54e-a7e554c935a5",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("ASP.NET_API.Model.CartItem", b =>
                {
                    b.HasOne("ASP.NET_API.Model.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_API.Model.ShoppingCart", "ShoppingCart")
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("ASP.NET_API.Model.Order", b =>
                {
                    b.HasOne("ASP.NET_API.Model.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASP.NET_API.Model.OrderItem", b =>
                {
                    b.HasOne("ASP.NET_API.Model.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_API.Model.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ASP.NET_API.Model.Product", b =>
                {
                    b.HasOne("ASP.NET_API.Model.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("ASP.NET_API.Model.RefreshToken", b =>
                {
                    b.HasOne("ASP.NET_API.Model.AppUser", "UserName")
                        .WithOne("RefreshToken")
                        .HasForeignKey("ASP.NET_API.Model.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserName");
                });

            modelBuilder.Entity("ASP.NET_API.Model.ShoppingCart", b =>
                {
                    b.HasOne("ASP.NET_API.Model.AppUser", "User")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASP.NET_API.Model.WishList", b =>
                {
                    b.HasOne("ASP.NET_API.Model.AppUser", "User")
                        .WithOne("WishList")
                        .HasForeignKey("ASP.NET_API.Model.WishList", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ASP.NET_API.Model.WishListItem", b =>
                {
                    b.HasOne("ASP.NET_API.Model.Product", "Product")
                        .WithMany("WishListItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_API.Model.WishList", "WishList")
                        .WithMany("WishListItems")
                        .HasForeignKey("WishListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ASP.NET_API.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ASP.NET_API.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_API.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ASP.NET_API.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASP.NET_API.Model.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RefreshToken");

                    b.Navigation("ShoppingCarts");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("ASP.NET_API.Model.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ASP.NET_API.Model.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("WishListItems");
                });

            modelBuilder.Entity("ASP.NET_API.Model.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ASP.NET_API.Model.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ASP.NET_API.Model.WishList", b =>
                {
                    b.Navigation("WishListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
